### PR TITLE
New design !

### PR DESCRIPTION
**Pull request by thomasbnt**
New design
image
image

- Added "**what is Library of Twitter**" part
- (WIP text) Added "**Contribute to this project**" part
- Added some **CSS** like cards, text fonts, responsive, colors and links
- Edited **function publish()** with a condition

If you want, I created a [draft on Figma](https://www.figma.com/file/pGTe0mp3wncnohQ4nUTNzH/LibraryOfTwitter?node-id=0%3A1)

### CODE REVIEW

**Comment by thomasbnt** [comment]
Maybe this PR resolve https://github.com/rocambille/library-of-twitter/issues/9 ? @rocambille

**Comment by thomasbnt** [comment]
If the text isn't generated and we click to **Tweet**, you've got that 
image

**Comment by rocambille** [comment]
amazing :star_struck: 

yes, solved #9

**Comment by thomasbnt** [comment]
Miss some content to the right card, if you have any idea 👍🏼📚

**Pull request merged**
